<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductVariantSpecSeeder extends Seeder
{
    /**
     * Seeder detail katalog WTC Cell.
     * Menambahkan/memperbarui varian dan spesifikasi untuk 32 HP.
     * Jalankan setelah ProductSeeder.
     */
    public function run(): void
    {
        $catalog = [
            'iphone-air' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'SKY BLUE', 'price' => 16599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'SPACE BLACK', 'price' => 16599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'SKY BLUE', 'price' => 20599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'SPACE BLACK', 'price' => 20599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 1024, 'color' => 'SKY BLUE', 'price' => 25599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 1024, 'color' => 'SPACE BLACK', 'price' => 25599000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Apple A19 Pro (3 nm)'],
                    ['Display', '6.5-inch LTPO Super Retina XDR OLED, 120Hz'],
                    ['Battery', '3149 mAh'],
                    ['OS', 'iOS 26'],
                    ['Resolution', '1260 x 2736 pixels'],
                    ['Main Camera', '48 MP'],
                    ['Front Camera', '18 MP'],
                    ['Weight', '165 g'],
                ],
            ],
            'iphone-17-pro-max' => [
                'variants' => [
                    ['ram' => null, 'storage' => 256, 'color' => 'SILVER', 'price' => 25999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 256, 'color' => 'DEEP BLUE', 'price' => 25999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 256, 'color' => 'COSMIC ORANGE', 'price' => 25999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'SILVER', 'price' => 29999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'DEEP BLUE', 'price' => 29999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'COSMIC ORANGE', 'price' => 29999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 1024, 'color' => 'SILVER', 'price' => 33999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 1024, 'color' => 'DEEP BLUE', 'price' => 33999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 1024, 'color' => 'COSMIC ORANGE', 'price' => 33999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 2048, 'color' => 'SILVER', 'price' => 38999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 2048, 'color' => 'DEEP BLUE', 'price' => 38999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 2048, 'color' => 'COSMIC ORANGE', 'price' => 38999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Apple A19 Pro'],
                    ['Display', '6.9-inch Super Retina XDR OLED, ProMotion up to 120Hz'],
                    ['Resolution', '2868 x 1320, 460 ppi'],
                    ['Rear Camera', '48MP Fusion Main + 48MP Ultra Wide + 48MP Telephoto'],
                    ['Front Camera', '18MP Center Stage'],
                    ['OS', 'iOS 26'],
                    ['Protection', 'IP68'],
                    ['Weight', '231 g'],
                ],
            ],
            'iphone-17-pro' => [
                'variants' => [
                    ['ram' => null, 'storage' => 256, 'color' => 'SILVER', 'price' => 22599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 256, 'color' => 'DEEP BLUE', 'price' => 22599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 256, 'color' => 'COSMIC ORANGE', 'price' => 22599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'SILVER', 'price' => 26599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'DEEP BLUE', 'price' => 26599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'COSMIC ORANGE', 'price' => 26599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 1024, 'color' => 'SILVER', 'price' => 30599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 1024, 'color' => 'DEEP BLUE', 'price' => 30599000, 'stock' => 10],
                    ['ram' => null, 'storage' => 1024, 'color' => 'COSMIC ORANGE', 'price' => 30599000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Apple A19 Pro'],
                    ['Display', '6.3-inch Super Retina XDR OLED, ProMotion up to 120Hz'],
                    ['Resolution', '2622 x 1206, 460 ppi'],
                    ['Rear Camera', '48MP Fusion Main + 48MP Ultra Wide + 48MP Telephoto'],
                    ['Front Camera', '18MP Center Stage'],
                    ['OS', 'iOS 26'],
                    ['Protection', 'IP68'],
                    ['Weight', '204 g'],
                ],
            ],
            'iphone-17' => [
                'variants' => [
                    ['ram' => null, 'storage' => 256, 'color' => 'BLACK', 'price' => 17999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 256, 'color' => 'WHITE', 'price' => 17999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 256, 'color' => 'LAVENDER', 'price' => 17999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'BLACK', 'price' => 21999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'WHITE', 'price' => 21999000, 'stock' => 10],
                    ['ram' => null, 'storage' => 512, 'color' => 'LAVENDER', 'price' => 21999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Apple A19'],
                    ['Display', '6.3-inch Super Retina XDR OLED, ProMotion up to 120Hz'],
                    ['Resolution', '2622 x 1206, 460 ppi'],
                    ['Rear Camera', '48MP Fusion Main + 48MP Ultra Wide'],
                    ['Front Camera', '18MP Center Stage'],
                    ['OS', 'iOS 26'],
                    ['Protection', 'IP68'],
                    ['Weight', '177 g'],
                ],
            ],
            'samsung-galaxy-z-flip-8' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'MINT', 'price' => 18249000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'GRAPHITE', 'price' => 18249000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLUE', 'price' => 18249000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'GRAPHITE', 'price' => 20249000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'MINT', 'price' => 20249000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLUE', 'price' => 20249000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Snapdragon 8 Elite Gen 5 for Galaxy'],
                    ['Display', '6.9-inch main AMOLED, 120Hz; 4.1-inch cover display'],
                    ['Rear Camera', '50MP Wide + 12MP Ultra Wide'],
                    ['Front Camera', '10MP'],
                    ['Battery', '4300 mAh'],
                    ['OS', 'Android 16 / One UI 8'],
                    ['Protection', 'IP48'],
                    ['Weight', '180 g'],
                ],
            ],
            'samsung-galaxy-z-fold-8-wide' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'CREAM', 'price' => 26499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'GRAPHITE', 'price' => 26499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'LAVENDER', 'price' => 26499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'GRAPHITE', 'price' => 28499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'CREAM', 'price' => 28499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'LAVENDER', 'price' => 28499000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'LAVENDER', 'price' => 32499000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'CREAM', 'price' => 32499000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'GRAPHITE', 'price' => 32499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Snapdragon 8 Elite Gen 5 for Galaxy'],
                    ['Display', '7.6-inch main AMOLED 120Hz; 6.5-inch cover display'],
                    ['Resolution', '2184 x 1968 main; 2520 x 1080 cover'],
                    ['Rear Camera', '50MP Wide + 12MP Ultra Wide + 10MP Telephoto'],
                    ['Battery', '4800 mAh'],
                    ['OS', 'Android 16 / One UI 8'],
                    ['Weight', '201 g'],
                    ['Protection', 'IP48'],
                ],
            ],
            'samsung-galaxy-z-fold-8-ultra' => [
                'variants' => [
                    ['ram' => 16, 'storage' => 512, 'color' => 'GRAPHITE', 'price' => 30299000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 512, 'color' => 'CREAM', 'price' => 30299000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'CREAM', 'price' => 34299000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'GRAPHITE', 'price' => 34299000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Snapdragon 8 Elite Gen 5 for Galaxy'],
                    ['Display', '8.0-inch main AMOLED 120Hz; 6.5-inch cover display'],
                    ['Rear Camera', '200MP Wide + 50MP Ultra Wide + 10MP Telephoto 3x'],
                    ['Battery', '5000 mAh, 45W wired charging'],
                    ['OS', 'Android 16 / One UI 8'],
                    ['Weight', '215 g'],
                    ['Protection', 'IP48'],
                ],
            ],
            'samsung-galaxy-a07-lte' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLACK', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'LIGHT BLUE', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'GREEN', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'BLACK', 'price' => 2899000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'LIGHT BLUE', 'price' => 2899000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'GREEN', 'price' => 2899000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'BLACK', 'price' => 3199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'LIGHT BLUE', 'price' => 3199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'GREEN', 'price' => 3199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLACK', 'price' => 3499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'LIGHT BLUE', 'price' => 3499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'GREEN', 'price' => 3499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Octa-Core, up to 2.2GHz'],
                    ['Display', '6.7-inch PLS LCD, 90Hz'],
                    ['Resolution', '720 x 1600'],
                    ['Rear Camera', '50MP + 2MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '5000 mAh'],
                    ['OS', 'Android 15 / One UI'],
                    ['Protection', 'IP54'],
                    ['Weight', '184 g'],
                ],
            ],
            'oppo-reno-16-pro-5g' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLACK', 'price' => 14499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'GREEN', 'price' => 14499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'WHITE', 'price' => 14499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 8550 SUPER'],
                    ['Display', '6.32-inch AMOLED, up to 144Hz'],
                    ['Rear Camera', '200MP Main + 50MP Telephoto + 8MP Ultra Wide'],
                    ['Front Camera', '50MP Ultra Wide'],
                    ['Battery', '6700 mAh'],
                    ['Charging', '80W SUPERVOOC'],
                    ['OS', 'ColorOS 16'],
                    ['Weight', '191 g'],
                ],
            ],
            'oppo-reno-16-5g' => [
                'variants' => [
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLACK', 'price' => 11549000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'GREEN', 'price' => 11549000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'WHITE', 'price' => 11549000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLACK', 'price' => 12999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'GREEN', 'price' => 12999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'WHITE', 'price' => 12999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Qualcomm Snapdragon 7 Gen 4'],
                    ['Display', '6.32-inch Crystal Guard+ AMOLED, 120Hz'],
                    ['Rear Camera', '50MP Ultra Wide + 50MP Wide OIS + 50MP Telephoto OIS'],
                    ['Front Camera', '50MP'],
                    ['Battery', '6700 mAh'],
                    ['Charging', '80W SUPERVOOC'],
                    ['OS', 'ColorOS 16'],
                ],
            ],
            'oppo-reno-16-f' => [
                'variants' => [
                    ['ram' => 8, 'storage' => 128, 'color' => 'POP WHITE', 'price' => 7699000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'DREAM PURPLE', 'price' => 7699000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'BLUE', 'price' => 7699000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'DREAM PURPLE', 'price' => 8499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'POP WHITE', 'price' => 8499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLUE', 'price' => 8499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 7300-Energy'],
                    ['Display', '6.57-inch AMOLED, 120Hz'],
                    ['Rear Camera', '50MP Wide OIS + 50MP Telephoto OIS + 8MP Ultra Wide'],
                    ['Front Camera', '50MP'],
                    ['Battery', '7000 mAh'],
                    ['Charging', '80W SUPERVOOC'],
                    ['OS', 'ColorOS 16'],
                    ['Weight', '195–197 g'],
                ],
            ],
            'oppo-find-x9' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'SPACE BLACK', 'price' => 15999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'TITANIUM GREY', 'price' => 15999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'SILVER', 'price' => 15999000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 512, 'color' => 'TITANIUM GREY', 'price' => 17999000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 512, 'color' => 'SPACE BLACK', 'price' => 17999000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 512, 'color' => 'SILVER', 'price' => 17999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 9500'],
                    ['Display', '6.59-inch AMOLED, 120Hz'],
                    ['Rear Camera', '50MP Wide OIS + 50MP Telephoto OIS + 50MP Ultra Wide + 2MP Mono'],
                    ['Front Camera', '32MP'],
                    ['Battery', '7025 mAh'],
                    ['Charging', '80W SUPERVOOC / 50W AIRVOOC'],
                    ['OS', 'ColorOS 16'],
                    ['Weight', '203 g'],
                ],
            ],
            'vivo-y31d' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 128, 'color' => 'PUTIH SATIN', 'price' => 3499000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'SATIN WHITE', 'price' => 3499000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'DIAMOND BLACK', 'price' => 3499000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'OCEAN BLUE', 'price' => 3499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Qualcomm Snapdragon 685'],
                    ['Display', '6.75-inch LCD, 120Hz'],
                    ['Resolution', '1570 x 720'],
                    ['Rear Camera', '50MP Wide + 2MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '7200 mAh'],
                    ['Charging', '44W'],
                    ['OS', 'Android 16 / OriginOS 6'],
                    ['Protection', 'IP68 & IP69'],
                    ['Weight', '219 g'],
                ],
            ],
            'vivo-x300-ultra' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLACK', 'price' => 25299000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'WHITE', 'price' => 25299000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLUE', 'price' => 25299000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'BLACK', 'price' => 29299000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'WHITE', 'price' => 29299000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 1024, 'color' => 'BLUE', 'price' => 29299000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Snapdragon 8 Elite Gen 5'],
                    ['Display', '6.82-inch 2K ZEISS Master Color, 1–144Hz'],
                    ['Rear Camera', '50MP Ultra Wide + 200MP 35mm + 200MP 85mm Telephoto, all OIS'],
                    ['Front Camera', '50MP'],
                    ['Battery', '6600 mAh'],
                    ['Charging', '100W FlashCharge'],
                    ['OS', 'OriginOS 6'],
                    ['Protection', 'IP68 & IP69'],
                ],
            ],
            'vivo-x300' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'MIST BLUE', 'price' => 14599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'PHANTOM BLACK', 'price' => 14599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'WHITE', 'price' => 14599000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 512, 'color' => 'PHANTOM BLACK', 'price' => 16999000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 512, 'color' => 'MIST BLUE', 'price' => 16999000, 'stock' => 10],
                    ['ram' => 16, 'storage' => 512, 'color' => 'WHITE', 'price' => 16999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 9500'],
                    ['Display', '6.31-inch AMOLED, 120Hz'],
                    ['Resolution', '2640 x 1216'],
                    ['Rear Camera', '200MP + 50MP + 50MP'],
                    ['Front Camera', '50MP'],
                    ['Battery', '6040 mAh'],
                    ['Charging', '90W FlashCharge'],
                    ['OS', 'Android 16 / OriginOS 6'],
                    ['Protection', 'IP68 & IP69'],
                ],
            ],
            'vivo-y31d-pro' => [
                'variants' => [
                    ['ram' => 6, 'storage' => 128, 'color' => 'PUTIH SATIN', 'price' => 4299000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'SATIN WHITE', 'price' => 4299000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'DIAMOND BLACK', 'price' => 4299000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'OCEAN BLUE', 'price' => 4299000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'HITAM PERMATA', 'price' => 4899000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'SATIN WHITE', 'price' => 4899000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'DIAMOND BLACK', 'price' => 4899000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'OCEAN BLUE', 'price' => 4899000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'PUTIH SATIN', 'price' => 5499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'SATIN WHITE', 'price' => 5499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'DIAMOND BLACK', 'price' => 5499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'OCEAN BLUE', 'price' => 5499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Qualcomm Snapdragon 685'],
                    ['Display', '6.75-inch LCD, 120Hz'],
                    ['Resolution', '1570 x 720'],
                    ['Rear Camera', '50MP Wide + 2MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '7000 mAh'],
                    ['Charging', '90W'],
                    ['OS', 'Android 16 / OriginOS 6'],
                    ['Protection', 'IP68 & IP69'],
                    ['Weight', '219 g'],
                ],
            ],
            'realme-c100i' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLACK', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLUE', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'GREEN', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 256, 'color' => 'BLACK', 'price' => 2799000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 256, 'color' => 'BLUE', 'price' => 2799000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 256, 'color' => 'GREEN', 'price' => 2799000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'BLACK', 'price' => 2999000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'BLUE', 'price' => 2999000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'GREEN', 'price' => 2999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Unisoc T7250'],
                    ['Display', '6.8-inch LCD, 120Hz'],
                    ['Resolution', '720 x 1570'],
                    ['Rear Camera', '8MP'],
                    ['Front Camera', '5MP'],
                    ['Battery', '7000 mAh'],
                    ['Charging', '15W'],
                    ['OS', 'Android 16 / realme UI'],
                    ['Weight', '208 g'],
                ],
            ],
            'realme-note-80' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 64, 'color' => 'BLACK', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 64, 'color' => 'WHITE', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 64, 'color' => 'BLUE', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLACK', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'WHITE', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLUE', 'price' => 2599000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Unisoc T7250'],
                    ['Display', '6.74-inch LCD, 90Hz'],
                    ['Resolution', '720 x 1600'],
                    ['Rear Camera', '8MP'],
                    ['Front Camera', '5MP'],
                    ['Battery', '6300 mAh'],
                    ['Charging', '15W'],
                    ['OS', 'Android / realme UI'],
                    ['Weight', '219 g'],
                ],
            ],
            'realme-c85-pro' => [
                'variants' => [
                    ['ram' => 8, 'storage' => 128, 'color' => 'BLACK', 'price' => 3999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'GOLD', 'price' => 3999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'GREEN', 'price' => 3999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLACK', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'GOLD', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'GREEN', 'price' => 4499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Qualcomm Snapdragon 685'],
                    ['Display', '6.8-inch AMOLED, 120Hz'],
                    ['Resolution', '1080 x 2344'],
                    ['Rear Camera', '50MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '7000 mAh'],
                    ['Charging', '45W'],
                    ['OS', 'Android 15 / realme UI 6.0'],
                    ['Protection', 'IP69 Pro'],
                    ['Weight', '205 g'],
                ],
            ],
            'realme-c85-4g' => [
                'variants' => [
                    ['ram' => 6, 'storage' => 128, 'color' => 'BLACK', 'price' => 3299000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'BLUE', 'price' => 3299000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'PURPLE', 'price' => 3299000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLACK', 'price' => 3799000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLUE', 'price' => 3799000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'PURPLE', 'price' => 3799000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Unisoc T8300'],
                    ['Display', '6.8-inch LCD, 144Hz'],
                    ['Rear Camera', '50MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '7000 mAh'],
                    ['Charging', '45W'],
                    ['OS', 'Android / realme UI'],
                    ['Protection', 'IP69 Pro'],
                ],
            ],
            'xiaomi-redmi-a7-pro' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 64, 'color' => 'BLACK', 'price' => 1949000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 64, 'color' => 'MIST BLUE', 'price' => 1949000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 64, 'color' => 'GREEN', 'price' => 1949000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'MIST BLUE', 'price' => 2199000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLACK', 'price' => 2199000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'GREEN', 'price' => 2199000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Unisoc T7250'],
                    ['Display', '6.9-inch LCD, up to 120Hz'],
                    ['Resolution', '1600 x 720'],
                    ['Rear Camera', '13MP + auxiliary sensor'],
                    ['Front Camera', '8MP'],
                    ['Battery', '6000 mAh'],
                    ['Charging', '15W'],
                    ['OS', 'Xiaomi HyperOS 3'],
                    ['Weight', '208 g'],
                ],
            ],
            'xiaomi-17t-pro' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLACK', 'price' => 12649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLUE', 'price' => 12649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'SILVER', 'price' => 12649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLACK', 'price' => 14649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLUE', 'price' => 14649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'SILVER', 'price' => 14649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 1024, 'color' => 'BLACK', 'price' => 16649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 1024, 'color' => 'BLUE', 'price' => 16649000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 1024, 'color' => 'SILVER', 'price' => 16649000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 9500'],
                    ['Display', '6.83-inch AMOLED, up to 144Hz'],
                    ['Resolution', '2772 x 1280'],
                    ['Rear Camera', '50MP Main + 50MP Periscope + 50MP Ultra Wide'],
                    ['Front Camera', '32MP'],
                    ['Battery', '7000 mAh'],
                    ['Charging', '100W wired / 50W wireless'],
                    ['OS', 'Xiaomi HyperOS'],
                    ['Weight', '219 g'],
                ],
            ],
            'xiaomi-17t' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLACK', 'price' => 9999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLUE', 'price' => 9999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'GREEN', 'price' => 9999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLUE', 'price' => 11999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLACK', 'price' => 11999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'GREEN', 'price' => 11999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 8500-Ultra'],
                    ['Display', '6.59-inch AMOLED, up to 120Hz'],
                    ['Resolution', '2756 x 1268'],
                    ['Rear Camera', '50MP Main + 50MP Periscope + 12MP Ultra Wide'],
                    ['Front Camera', '32MP'],
                    ['Battery', '6500 mAh'],
                    ['Charging', '67W HyperCharge'],
                    ['OS', 'Xiaomi HyperOS'],
                    ['Weight', '200 g'],
                ],
            ],
            'xiaomi-17' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLACK', 'price' => 14599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLUE', 'price' => 14599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'WHITE', 'price' => 14599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLACK', 'price' => 16599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLUE', 'price' => 16599000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'WHITE', 'price' => 16599000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'Snapdragon 8 Elite Gen 5'],
                    ['Display', '6.3-inch OLED, 1–120Hz'],
                    ['Resolution', '2656 x 1220'],
                    ['Rear Camera', '50MP Main + 50MP Floating Telephoto + 50MP Ultra Wide'],
                    ['Front Camera', '50MP AF'],
                    ['Battery', '6330 mAh'],
                    ['Charging', '100W wired / 50W wireless'],
                    ['OS', 'Xiaomi HyperOS'],
                    ['Weight', '191 g'],
                ],
            ],
            'infinix-hot-70' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLACK', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLUE', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'GREEN', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'BLACK', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'BLUE', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'GREEN', 'price' => 2599000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLACK', 'price' => 2999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLUE', 'price' => 2999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'GREEN', 'price' => 2999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Helio G100 Ultimate'],
                    ['Display', '6.78-inch IPS LCD, 120Hz'],
                    ['Resolution', '720 x 1576'],
                    ['Rear Camera', '50MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '6000 mAh'],
                    ['Charging', '45W'],
                    ['OS', 'Android 16 / XOS 16'],
                    ['Network', '4G'],
                ],
            ],
            'infinix-gt-50-pro' => [
                'variants' => [
                    ['ram' => 12, 'storage' => 256, 'color' => 'BLACK', 'price' => 6799000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'SILVER', 'price' => 6799000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'ORANGE', 'price' => 6799000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'BLACK', 'price' => 7799000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'SILVER', 'price' => 7799000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 512, 'color' => 'ORANGE', 'price' => 7799000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 8400 Ultimate'],
                    ['Display', '6.78-inch AMOLED, 1.5K, 144Hz'],
                    ['Rear Camera', '50MP Main + 8MP Ultra Wide'],
                    ['Front Camera', '13MP'],
                    ['Battery', '6500 mAh'],
                    ['Charging', '45W wired / 30W wireless'],
                    ['OS', 'Android 16 / XOS 16'],
                    ['Network', '5G'],
                ],
            ],
            'infinix-smart-20' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 64, 'color' => 'BLACK', 'price' => 1849000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 64, 'color' => 'BLUE', 'price' => 1849000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 64, 'color' => 'ORANGE', 'price' => 1849000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLUE', 'price' => 1999000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLACK', 'price' => 1999000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'ORANGE', 'price' => 1999000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 256, 'color' => 'ORANGE', 'price' => 2299000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 256, 'color' => 'BLACK', 'price' => 2299000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 256, 'color' => 'BLUE', 'price' => 2299000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Helio G81 Ultimate'],
                    ['Display', '6.78-inch IPS LCD, 120Hz'],
                    ['Resolution', '720 x 1576'],
                    ['Rear Camera', '8MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '5200 mAh'],
                    ['Charging', '15W supported'],
                    ['OS', 'Android 16 / XOS 16'],
                    ['Protection', 'IP64'],
                ],
            ],
            'infinix-note-60' => [
                'variants' => [
                    ['ram' => 8, 'storage' => 128, 'color' => 'BLACK', 'price' => 4999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'TITANIUM GREY', 'price' => 4999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'GREEN', 'price' => 4999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'BLACK', 'price' => 4999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'TITANIUM GREY', 'price' => 4999000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'GREEN', 'price' => 4999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 7400 Ultimate'],
                    ['Display', '6.78-inch AMOLED, 144Hz'],
                    ['Resolution', '1208 x 2644'],
                    ['Rear Camera', '50MP OIS + 8MP Ultra Wide'],
                    ['Front Camera', '13MP'],
                    ['Battery', '6500 mAh'],
                    ['Charging', '45W wired / 30W wireless'],
                    ['OS', 'Android 16 / XOS 16'],
                    ['Protection', 'IP64'],
                    ['Weight', '199 g'],
                ],
            ],
            'tecno-pova-8-5g' => [
                'variants' => [
                    ['ram' => 6, 'storage' => 128, 'color' => 'ARC WHITE', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'GRAPHITE BLACK', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 6, 'storage' => 128, 'color' => 'HELIOS ORANGE', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'GRAPHITE BLACK', 'price' => 5199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'ARC WHITE', 'price' => 5199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'HELIOS ORANGE', 'price' => 5199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'HELIOS ORANGE', 'price' => 5799000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'ARC WHITE', 'price' => 5799000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'GRAPHITE BLACK', 'price' => 5799000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Dimensity 7100 5G'],
                    ['Display', '6.76-inch IPS LCD, 144Hz'],
                    ['Resolution', '2344 x 1080'],
                    ['Rear Camera', '50MP AF'],
                    ['Front Camera', '13MP'],
                    ['Battery', '8000 mAh'],
                    ['Charging', '45W'],
                    ['OS', 'Android 16 / HiOS 16'],
                    ['Weight', '225 g'],
                ],
            ],
            'tecno-spark-50' => [
                'variants' => [
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLACK', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'WHITE', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 4, 'storage' => 128, 'color' => 'BLUE', 'price' => 2399000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'BLACK', 'price' => 2799000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'WHITE', 'price' => 2799000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'BLUE', 'price' => 2799000, 'stock' => 10],
                ],
                'specs' => [
                    ['Display', '6.78-inch LCD, 120Hz'],
                    ['Rear Camera', '50MP'],
                    ['Front Camera', '8MP'],
                    ['Battery', '7000 mAh'],
                    ['Charging', '18W'],
                    ['OS', 'Android 16 / HiOS 16'],
                    ['Network', '4G'],
                    ['Features', 'FreeLink 2.0; drop resistance'],
                ],
            ],
            'tecno-camon-50-pro' => [
                'variants' => [
                    ['ram' => 8, 'storage' => 256, 'color' => 'MOONSHADOW BLACK', 'price' => 5499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'MALACHITE GREEN', 'price' => 5499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'NEBULA TITANIUM', 'price' => 5499000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Helio G200 Ultimate'],
                    ['Display', '6.78-inch Curved AMOLED, 144Hz, 1.5K'],
                    ['Resolution', '1208 x 2644'],
                    ['Rear Camera', '50MP OIS + 50MP 3X + 8MP Ultra Wide'],
                    ['Front Camera', '32MP'],
                    ['Battery', '6500 mAh'],
                    ['Charging', '45W'],
                    ['OS', 'Android / HiOS 16'],
                    ['Network', '4G'],
                ],
            ],
            'tecno-camon-50' => [
                'variants' => [
                    ['ram' => 8, 'storage' => 128, 'color' => 'MOONSHADOW BLACK', 'price' => 4199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'MALACHITE GREEN', 'price' => 4199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 128, 'color' => 'NEBULA TITANIUM', 'price' => 4199000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'MALACHITE GREEN', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'MOONSHADOW BLACK', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 8, 'storage' => 256, 'color' => 'NEBULA TITANIUM', 'price' => 4499000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'NEBULA TITANIUM', 'price' => 4999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'MOONSHADOW BLACK', 'price' => 4999000, 'stock' => 10],
                    ['ram' => 12, 'storage' => 256, 'color' => 'MALACHITE GREEN', 'price' => 4999000, 'stock' => 10],
                ],
                'specs' => [
                    ['Chipset', 'MediaTek Helio G200 Ultimate'],
                    ['Display', '6.78-inch AMOLED, 144Hz, 1.5K'],
                    ['Resolution', '1208 x 2644'],
                    ['Rear Camera', '50MP OIS + 8MP Ultra Wide'],
                    ['Front Camera', '32MP'],
                    ['Battery', '6500 mAh'],
                    ['Charging', '45W'],
                    ['OS', 'Android / HiOS 16'],
                    ['Network', '4G'],
                ],
            ],
        ];

        foreach ($catalog as $slug => $data) {
            $product = Product::where('slug', $slug)->first();

            if (!$product) {
                continue;
            }

            $product->variants()->delete();
            foreach ($data['variants'] as $variant) {
                $product->variants()->create([
                    'ram' => $variant['ram'],
                    'storage' => $variant['storage'],
                    'color' => $variant['color'],
                    'price' => $variant['price'],
                    'stock' => $variant['stock'],
                    'is_active' => true,
                ]);
            }

            $product->specs()->delete();
            foreach ($data['specs'] as $i => [$label, $value]) {
                $product->specs()->create([
                    'label' => $label,
                    'value' => $value,
                    'sort_order' => $i + 1,
                ]);
            }
        }
    }
}
